### ISSUE TITLE
Publish source to npm

### ISSUE THREAD

**Issue by lights0123** [geospoc/v-mapbox#175]
Currently, source files are removed from the published build. However, things like [Nuxt Components](https://github.com/nuxt/components) can use them to automatically import components, with automatic tree-shaking configuration.

**Comment by vinayakkulkarni** [comment]
I've fixed this in #179 & updated a codesandbox so that you can test it 😃 

[![Edit v-mapbox-map-demo](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/v-mapbox-map-demo-k1l1n?fontsize=14&hidenavigation=1&theme=dark)

>  However, things like Nuxt Components can use them to automatically import components, with automatic tree-shaking configuration.

Hmm, this can be a good feature but currently working on migrating the codebase to support vue 3. Hopefully by then Nuxt 3 will be out too :)
