### ISSUE TITLE
TypeError: this.templateRefs is undefined

### ISSUE THREAD

**Issue by iBobik** [geospoc/v-mapbox#590]
Map stopped working after upgrade to 1.9.0. Tried also in the clean project: https://codesandbox.io/s/sweet-bose-63182

Uncaught (in promise) TypeError: this.templateRefs is undefined
    _loadMap v-mapbox.esm.js:1291
    _loadMap v-mapbox.esm.js:1287
    promise callback*$_loadMap v-mapbox.esm.js:1285
    mounted v-mapbox.esm.js:1420
    VueJS 11
    <anonymous> main.js:6
    js app.js:1148
    __webpack_require__ app.js:849
    fn app.js:151
    1 app.js:1161
    __webpack_require__ app.js:849
    checkDeferredModules app.js:46
    <anonymous> app.js:925
    <anonymous> app.js:928

**Comment by AlJaMa** [comment]
I've found the same issues as @iBobik. It presents as `Missing required prop: "container"`. 
Starting a new project with Vue2, this appears to occur with 1.9.0, 1.8.2, 1.8.1, 1.8.0. 

Reverting to 1.7.3 the issue is no longer present.

Other relevant dependencies were held constant as v-mapbox was varied. 
```
"@vue/composition-api": "^1.4.0",
"map-promisified": "^0.4.0",
"mapbox-gl": "^1.13.1",
"v-mapbox": "1.7.3",
"vue": "^2.6.11",
```

**Comment by vinayakkulkarni** [comment]
You need to have `@vue/composition-api` as a devDep or dep when using `v-mapbox v1.x`
